=== zxqw1541/javaexam/0xml01/step02/test05.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 5) 엘리먼트의 개수 지정
  => 개수를 지정하지 않으면 필수
  => ? : 0 또는 1
  => * : 0 이상
  => + : 1 이상
-->
<!ELEMENT student (name,age?,tel+,address*)>
<!ELEMENT name    (#PCDATA)>
<!ELEMENT age     (#PCDATA)>
<!ELEMENT tel     (#PCDATA)>
<!ELEMENT address (#PCDATA)>

=== zxqw1541/javaexam/0xml01/step02/test05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "test05.dtd">
<!-- 자식 엘리먼트가 나열된 순서대로 작성해야 한다. -->

<!-- 정상적인 예제 -->
<!--  
<student>
  <name></name>
  <tel></tel>
</student>
-->

<!--  
<student>
  <name></name>
  <age></age>
  <tel></tel>
</student>
-->

<student>
  <name></name>
  <age></age>
  <tel></tel>
  <tel></tel>
  <tel></tel>
  <tel></tel>
  <address></address>
  <address></address>
  <address></address>
  <address></address>
  <address></address>
</student>
